ruby_version:
 - 'ruby-2.4.0'
bundler_version: 1.13.7
tool_config:
  gcc:
    version: '4.8'
test_pattern:
  - spec/**_spec.rb
test_exclude_pattern:
  - spec/agent_spec.rb
tests:
  - bundle exec rspec spec/agent_spec.rb
cache:
  per_profile: true
  key_paths:
    - Gemfile
    - Gemfile.lock
    - solano.gemspec
    - lib/solano/version.rb
